from pathlib import Path

changes = {
    'src/data/fisheriesCrosscutting.ts': {
        "{ parameter: 'দ্রবীভূত অক্সিজেন (DO)', healthyRange: '৫ – ৮ mg/L', redFlagLevel: '< ৩.০ mg/L (মাছ ভোরের দিকে ভাসবে)', emergencyAction: '🚨 অবিলম্বে এয়ারেটর বা পাম্প চালান, বাঁশ দিয়ে পানি পিটিয়ে অক্সিজেন বাড়ান, খাবার বন্ধ রাখুন।' }": "{ parameter: 'Dissolved Oxygen (DO)', healthyRange: '5 – 8 mg/L', redFlagLevel: '< 3.0 mg/L (fish may surface in the morning)', emergencyAction: '🚨 Run aerator or pump immediately, stir water with bamboo for oxygen, and stop feeding.' },",
        "{ parameter: 'পানির অম্লতা (pH)', healthyRange: '৬.৫ – ৮.৫', redFlagLevel: '< ৬.০ (অ্যাসিডিক) বা > ৯.০ (ক্ষারীয়)', emergencyAction: 'কম pH এ শতকে ১-২ কেজি কৃষি চুন দিন। বেশি pH এ চুন বন্ধ রেখে কিছুটা পানি বদলান।' }": "{ parameter: 'Water Acidity (pH)', healthyRange: '6.5 – 8.5', redFlagLevel: '< 6.0 (acidic) or > 9.0 (alkaline)', emergencyAction: 'Add 1-2 kg agricultural lime per 100 decimals for low pH. For high pH, stop lime and replace some water.' },",
        "{ parameter: 'পানির তাপমাত্রা (Temp)', healthyRange: '২৫ – ৩২°সে', redFlagLevel: '< ২০°সে বা > ৩৫°সে', emergencyAction: 'তাপমাত্রা বেশি হলে খাবার অর্ধেক কমিয়ে দিন এবং পুকুরে ছায়ার ব্যবস্থা/পানি বাড়ান।' }": "{ parameter: 'Water Temperature (Temp)', healthyRange: '25 – 32°C', redFlagLevel: '< 20°C or > 35°C', emergencyAction: 'If temperature is high, reduce feed by half and provide shade or more water.' },",
        "{ parameter: 'অ্যামোনিয়া (Ammonia)', healthyRange: '< ০.১ mg/L', redFlagLevel: '> ০.৫ mg/L (ফুলকা লাল হয়ে পচা)', emergencyAction: 'খাবার দেওয়া ২ দিন বন্ধ রাখুন, তলার কাদা নাড়াবেন না, ৩০% পানি পরিবর্তন করুন।' }": "{ parameter: 'Ammonia', healthyRange: '< 0.1 mg/L', redFlagLevel: '> 0.5 mg/L (gill damage and rotten smell)', emergencyAction: 'Stop feeding for 2 days, avoid stirring bottom sludge, and change 30% of the water.' },",
        "{ parameter: 'পানির স্বচ্ছতা (Secchi Depth)', healthyRange: '২৫ – ৪০ সেমি', redFlagLevel: '< ১৫ সেমি (ঘন সবুজ) বা > ৫০ সেমি (একদম পরিষ্কার)', emergencyAction: 'খুব পরিষ্কার হলে সার/খাবার দিন। অতিরিক্ত সবুজ হলে চুন ও জিওলাইট দিন।' }": "{ parameter: 'Water Clarity (Secchi Depth)', healthyRange: '25 – 40 cm', redFlagLevel: '< 15 cm (dense green) or > 50 cm (very clear)', emergencyAction: 'If water is too clear, add fertilizer or feed. If too green, add lime and zeolite.' },",
        "'১. পুকুর শুকানো: তলার কাদা শুকিয়ে ৭–১৫ দিন রোদে ফেটে যেতে দিন।'": "'1. Dry the pond: expose bottom mud to sunlight for 7–15 days until it cracks.',",
        "'২. রাক্ষুসে মাছ অপসারণ: সেচ বা রোটেনন প্রয়োগ করে রাক্ষস মাছ (শোল, বোয়াল) দূর করুন।'": "'2. Remove predators: apply sevin or rotenone to remove predator fish (Shol, Boal).',",
        "'৩. চুন প্রয়োগ: শতকে ১–১.৫ কেজি কৃষি চুন সমস্ত তলদেশে ছিটান।'": "'3. Apply lime: spread 1–1.5 kg agricultural lime per 100 decimals across the pond bottom.',",
        "'৪. জৈব সার: চুন দেওয়ার ৫-৭ দিন পর শতকে ৫-৭ কেজি গোবর/কমপোস্ট দিন।'": "'4. Organic manure: add 5–7 kg of cow dung or compost per 100 decimals 5–7 days after liming.',",
        "'৫. পানি প্রবেশ ও স্থায়ীকরণ: ৫-৭ দিন পর পোনা ছাড়ার উপযোগী সবুজ প্লাংকটন তৈরি হবে।'": "'5. Water entry and stabilization: after 5–7 days, green plankton suitable for fry release will develop.',",
        "'✓ সমান আকারের পোনা (ছোট-বড় পোনা থাকলে বড়গুলো ছোটগুলোকে খাবে)।'": "'✓ Uniform-size fry (unequal fry may result in larger fish eating smaller ones).',",
        "'✓ পানির স্রোতের বিপরীতে সতেজভাবে সাঁতার কাটে।'": "'✓ Swims actively against the current.',",
        "'✓ গায়ে কোনো লাল দাগ, ক্ষত, তুলার মতো ছত্রাক বা ছেঁড়া পাখনা নেই।'": "'✓ No red spots, wounds, fungal patches, or torn fins on the body.',",
        "'✓ চোখ স্বচ্ছ ও পেট স্বাভাবিক (ফোলা বা শুষ্ক নয়)।'": "'✓ Clear eyes and a normal belly (not swollen or shrunken).',",
        "'✓ মৎস্য অধিদপ্তর (DoF) নিবন্ধিত হ্যাচারি থেকে পোনা সংগ্রহ করুন।'": "'✓ Source fry from a DoF-registered hatchery.',",
        "'nationalHelpline: '১৬১২৩ (কৃষি কল সেন্টার)','": "'nationalHelpline: '16123 (Agriculture Call Center)',",
        "'upazilaOfficerLabel: 'উপজেলা মৎস্য কর্মকর্তা (UFO Office)','": "'upazilaOfficerLabel: 'Upazila Fisheries Officer (UFO Office)',",
        "'emergencyNotice: 'যদি প্রতিদিন ১%-এর বেশি মাছ ভাসতে বা মরতে শুরু করে, তবে দেরি না করে নিকটস্থ মৎস্য অফিসে বা ১৬১২৩ নম্বরে কল করুন।'": "'emergencyNotice: 'If more than 1% of fish begin floating or dying each day, contact the nearest fisheries office or call 16123 immediately.',",
    },
    'src/data/pondDepthMatrix.ts': {
        "depthZoneBn: 'উপরিভাগ (Surface Layer)'": "depthZoneBn: 'Surface Layer'",
        "rangeMeter: '০.০ – ০.৫ মিটার'": "rangeMeter: '0.0 – 0.5 m'",
        "solarPenetration: 'সর্বোচ্চ (১০০%)'": "solarPenetration: 'Maximum (100%)'",
        "dissolvedOxygen: 'সর্বোচ্চ (সালোকসংশ্লেষণ ও বাতাসের ঢেউ)'": "dissolvedOxygen: 'Highest (photosynthesis + air exchange)'",
        "primaryFood: 'ফাইটোপ্ল্যাংকটন, ভাসমান পোকা, জুওপ্ল্যাংকটন'": "primaryFood: 'Phytoplankton, floating insects, zooplankton'",
        "exampleSpecies: ['কাতলা (Catla)', 'সিলভার কার্প (Silver Carp)', 'সরপুঁটি (Silver Barb)', 'মলা (Mola)', 'খলিশা']": "exampleSpecies: ['Catla', 'Silver Carp', 'Silver Barb', 'Mola', 'Gourami']",
        "depthZoneBn: 'মধ্যস্তর (Column Layer)'": "depthZoneBn: 'Column Layer'",
        "rangeMeter: '০.৫ – ১.২ মিটার'": "rangeMeter: '0.5 – 1.2 m'",
        "solarPenetration: 'মাঝারি (৪০–৭০%)'": "solarPenetration: 'Moderate (40–70%)'",
        "dissolvedOxygen: 'মাঝারি থেকে উচ্চ'": "dissolvedOxygen: 'Moderate to high'",
        "primaryFood: 'বড় জুওপ্ল্যাংকটন, জলজ উদ্ভিদাংশ, ভাসমান ফিড'": "primaryFood: 'Large zooplankton, aquatic vegetation, floating feed'",
        "exampleSpecies: ['রুই (Rohu)', 'গ্রাস কার্প (Grass Carp)', 'বিগহেড কার্প', 'পাবদা (Pabda)', 'ভেটি/ভেটকি']": "exampleSpecies: ['Rohu', 'Grass Carp', 'Bighead Carp', 'Pabda', 'Barramundi']",
        "depthZoneBn: 'তলদেশ (Bottom Layer)'": "depthZoneBn: 'Bottom Layer'",
        "rangeMeter: '১.২ – ২.০+ মিটার'": "rangeMeter: '1.2 – 2.0+ m'",
        "solarPenetration: 'সর্বনিম্ন (<৩০%)'": "solarPenetration: 'Lowest (<30%)'",
        "dissolvedOxygen: 'সর্বনিম্ন (পচন ক্রিয়া)'": "dissolvedOxygen: 'Lowest (decomposition)'",
        "primaryFood: 'পচা জৈব বর্জ্য (Detritus), তলার শেওলা, কাদার পোকা'": "primaryFood: 'Detritus, bottom sludge, benthic invertebrates'",
        "exampleSpecies: ['মৃগেল (Mrigal)', 'কার্পিও (Common Carp)', 'কালিবাউশ (Kalibaus)', 'গলদা চিংড়ি (Prawn)', 'শিং/মাগুর']": "exampleSpecies: ['Mrigal', 'Common Carp', 'Kalibaus', 'Prawn', 'Shing / Magur']",
        "depthZoneBn: 'সীমানা/সর্বস্তর (Boundary / Air-Breathing Zone)'": "depthZoneBn: 'Boundary / Air-Breathing Zone'",
        "rangeMeter: 'পুকুরের চারপাশ ও কাদা'": "rangeMeter: 'Pond edge and muddy shallows'",
        "solarPenetration: 'পরিবর্তনশীল'": "solarPenetration: 'Variable'",
        "dissolvedOxygen: 'বায়ুশ্বাসী (অক্সিজেন কম হলেও সহনশীল)'": "dissolvedOxygen: 'Air-breathing tolerant (survives low O2)'",
        "primaryFood: 'ছোট মাছ, শামুক, কাদার পোকা, কমার্শিয়াল পিলেট'": "primaryFood: 'Small fish, snails, benthic insects, commercial pellets'",
        "exampleSpecies: ['তিলাপিয়া (Tilapia)', 'কৈ (Thai Koi)', 'শোল/টাকি', 'টেংরা/গুলশা', 'কুচিয়া (Mud Eel)']": "exampleSpecies: ['Tilapia', 'Thai Koi', 'Snakehead', 'Tengra / Gulsha', 'Mud Eel']",
    },
    'src/data/fisheriesSpecies.ts': {
        "stockingDensityHint: '৩০ - ৪০% (পুকুরের মধ্যস্তরের প্রধান মাছ)'": "stockingDensityHint: '30 - 40% (primary column layer stock)'",
        "notes: 'মেজর কার্পের মধ্যে অত্যন্ত জনপ্রিয়। পানির মধ্যস্তরের খাবার খায়।'": "notes: 'A very popular major carp species. Feeds in the pond mid-water layer.'",
        "stockingDensityHint: '২০ - ৩০% (পুকুরের উপরিভাগ)'": "stockingDensityHint: '20 - 30% (surface layer)'",
        "notes: 'পুকুরের উপরিভাগে দ্রুত বাড়ে। প্রাণিপ্ল্যাংকটন খায়।'": "notes: 'Grows rapidly in the surface layer and feeds on zooplankton.'",
        "stockingDensityHint: '২০ - ২৫% (পুকুরের তলদেশ)'": "stockingDensityHint: '20 - 25% (bottom layer)'",
        "notes: 'পুকুরের একদম নিচের স্তরের জৈব বর্জ্য ও পচা খাবার খেয়ে পুকুর পরিষ্কার রাখে।'": "notes: 'Consumes bottom-layer organic waste and decomposing feed to help keep the pond clean.'",
        "notes: 'পুকুরের ক্ষতিকর শেওলা ও সাইনোপ্লাংকটন খেয়ে পানির ভাসমান সবুজ ভাব নিয়ন্ত্রণে রাখে।'": "notes: 'Eats harmful algae and cyanobacteria to help control green water.'",
        "feedType: 'Napier grass, duckweed (খুদি পানা), aquatic weeds'": "feedType: 'Napier grass, duckweed, aquatic weeds'",
        "notes: 'পুকুরের জলজ আগাছা ও ঘাস খায়। ঘাস খাইয়ে দ্রুত ওজন বাড়ানো যায়।'": "notes: 'Feeds on aquatic weeds and grasses; can gain weight quickly when well-fed.'",
        "notes: 'তলার মাটি নাড়াচাড়া করে জমে থাকা ক্ষতিকর গ্যাস বের করে দেয়।'": "notes: 'Stirs bottom soil and releases trapped harmful gases.'",
        "notes: 'কাতলার সাথে প্রতিযোগিতা করতে পারে, তাই নিয়ন্ত্রিত সংখ্যায় মজুদ করতে হয়।'": "notes: 'Can compete with Catla, so stock in controlled numbers.'",
        "stockingDensityHint: 'বাণিজ্যিক একক চাষ (১০০-২০০ পোনা/শতাংশ)'": "stockingDensityHint: 'Commercial monoculture (100-200 fry/decimal)'",
        "notes: 'নিবিড় উচ্চ ঘনত্বের বাণিজ্যিকভাবে লাভজনক চাষযোগ্য মাছ।'": "notes: 'A commercially profitable species suitable for intensive high-density culture.'",
        "stockingDensityHint: 'একক বা মিশ্র চাষে ১৫-২০%'": "stockingDensityHint: '15-20% in monoculture or polyculture'",
        "notes: 'প্রতিকূল আবহাওয়া ও কম অক্সিজেনেও টিকে থাকতে পারে।'": "notes: 'Tolerant of adverse conditions and low oxygen.'",
        "stockingDensityHint: 'বাণিজ্যিক ডোবা/পুকুর একক চাষ (২০০-৩০০ পোনা/শতাংশ)'": "stockingDensityHint: 'Commercial pond monoculture (200-300 fry/decimal)'",
        "notes: 'অতিরিক্ত শ্বাসযন্ত্র আছে, অগভীর পুকুরেও চাষ সম্ভব।'": "notes: 'Has accessory breathing organs and can be grown in shallow ponds.'",
        "stockingDensityHint: 'একক চাষ (১৫০-২৫০ পোনা/শতাংশ)'": "stockingDensityHint: 'Monoculture (150-250 fry/decimal)'",
        "notes: 'উচ্চ পুষ্টিগুণ ও বাজারমূল্যের দেশীয় শিং মাছ।'": "notes: 'A nutritious, high-value native Shing catfish.'",
        "stockingDensityHint: 'একক চাষ (১০০-২০০ পোনা/শতাংশ)'": "stockingDensityHint: 'Monoculture (100-200 fry/decimal)'",
        "notes: 'রোগীর পথ্য হিসেবে বিখ্যাত দেশীয় সুস্বাদু মাগুর মাছ।'": "notes: 'A native Magur catfish prized as medicinal and delicious.'",
        "stockingDensityHint: 'মিশ্ৰ চাষে ১০-১৫%'": "stockingDensityHint: '10-15% in polyculture'",
        "notes: 'অত্যন্ত চড়া বাজারমূল্যের সুস্বাদু ক্যাটফিশ।'": "notes: 'A premium-market gourmet catfish.'",
        "stockingDensityHint: 'মুক্ত জলাশয়/হাওর শিকারি মাছ'": "stockingDensityHint: 'Floodplain/riverine predator fish'",
        "notes: 'শিকারি মাছ। সাধারণ মিশ্র চাষের পুকুরে অন্য পোনা খেয়ে ফেলে।'": "notes: 'A predator fish that may eat other stocked fry in a standard mixed pond.'",
        "stockingDensityHint: 'নদী ও হাওর থেকে আহরণকৃত'": "stockingDensityHint: 'Collected from rivers and haors'",
        "notes: 'নদীর তলার সুস্বাদু শিকারি ক্যাটফিশ।'": "notes: 'A prized river-bottom predator catfish.'",
        "stockingDensityHint: 'গভীর হাওর ও দিঘি'": "stockingDensityHint: 'Deep haors and ponds'",
        "notes: 'গভীর পানির নিশাচর শিকারি মাছ।'": "notes: 'A nocturnal predator fish of deep water.'",
        "stockingDensityHint: 'নিষিদ্ধ (চাষ সম্পূর্ণ অবৈধ)'": "stockingDensityHint: 'Banned (culture fully illegal)'",
        "notes: '⚠️ বাংলাদেশে থাই/আফ্রিকান মাগুর চাষ ও বিক্রি আইনত সম্পূর্ণ নিষিদ্ধ। পরিবেশ ও জীববৈচিত্র্যের জন্য অত্যন্ত ক্ষতিকর।'": "notes: '⚠️ Thai/African Magur farming and sale are legally banned in Bangladesh. Extremely harmful to the environment and biodiversity.'",
        "stockingDensityHint: '১০ - ২০%'": "stockingDensityHint: '10 - 20%'",
        "notes: 'দ্রুত বাড়ে এবং পুকুরের নরম আগাছা খায়।'": "notes: 'Grows fast and consumes soft pond weeds.'",
        "stockingDensityHint: '৫ - ১০% (SIS স্বতঃস্ফূর্তি চাষ)'": "stockingDensityHint: '5 - 10% (SIS natural culture)'",
        "notes: 'প্রচুর ক্যালসিয়াম ও ভিটামিন সমৃদ্ধ দেশীয় ছোট মাছ।'": "notes: 'A native small fish rich in calcium and vitamins.'",
        "notes: 'উচ্চ বাজারমূল্যের ছোট ক্যাটফিশ।'": "notes: 'A high-value small catfish.'",
        "stockingDensityHint: 'অগভীর জলাশয় ও হাওর'": "stockingDensityHint: 'Shallow wetlands and haors'",
        "notes: 'বায়ুশ্বাসী শিকারি মাছ। শক্ত ও সহনশীল।'": "notes: 'An air-breathing predator fish. Tough and resilient.'",
        "stockingDensityHint: 'উপকূলীয় ঘের (১০-২০ পোনা/বর্গমিটার)'": "stockingDensityHint: 'Coastal pens (10-20 fry/m²)'",
        "notes: 'খুলনা, সাতক্ষীরা ও বাগেরহাটের প্রধান রপ্তানিযোগ্য লোনা পানির চিংড়ি।'": "notes: 'A major saline-water export shrimp from Khulna, Satkhira, and Bagerhat.'",
        "stockingDensityHint: 'ঘের/পুকুরে ১০ - ২০%'": "stockingDensityHint: '10 - 20% in ponds or pens'",
        "notes: 'মিঠা পানির সবচেয়ে মূল্যবান চিংড়ি। কার্পের সাথে সমন্বিত চাষ উপযোগী।'": "notes: 'The most valuable freshwater prawn. Suitable for integrated culture with carp.'",
        "stockingDensityHint: 'উপকূলীয় খাঁচা/খামার'": "stockingDensityHint: 'Coastal cages/farms'",
        "notes: 'উপকূলীয় মোটাতাজাকরণ ও রপ্তানি সম্ভাবনা।'": "notes: 'Coastal fattening and export potential.'",
        "stockingDensityHint: 'উপকূলীয় পিসি কালচার'": "stockingDensityHint: 'Coastal brackish culture'",
        "notes: 'লোনা ও ইষৎ লোনা পানির দামি শিকারি মাছ।'": "notes: 'A premium predator fish of saline and slightly brackish water.'",
        "stockingDensityHint: 'পুকুর চাষে ১০%'": "stockingDensityHint: '10% in pond culture'",
        "notes: 'নোট: সামুদ্রিক আসল রূপচাঁদার সাথে বিভ্রান্ত হবেন না (সমুদ্রের আসল রূপচাঁদা আলাদা)।'": "notes: 'Note: Do not confuse with true marine Silver Pomfret (a different species).',",
        "notes: 'মেজর কার্পের চেয়ে অধিক রোগপ্রতিরোধ ক্ষমতাসম্পন্ন দেশীয় মাছ।'": "notes: 'A native fish more disease resistant than major carp.'",
        "notes: 'দেশীয় মাইনর কার্প।'": "notes: 'A native minor carp.'",
        "stockingDensityHint: 'হাওর ও বিলের মাছ'": "stockingDensityHint: 'Haor and beel fish'",
        "notes: 'দেশীয় নদী-বিলের মাইনর কার্প।'": "notes: 'A native minor riverine and wetland carp.'",
        "stockingDensityHint: 'কার্পের সাথে মিশ্র চাষ (৫-১০%)'": "stockingDensityHint: 'Mixed culture with carp (5-10%)'",
        "notes: 'প্রচুর ভিটামিন-এ সমৃদ্ধ। অন্ধত্ব প্রতিরোধে বাচ্চাদের জন্য অত্যন্ত উপকারী।'": "notes: 'Rich in vitamin A and highly beneficial for preventing blindness in children.'",
        "stockingDensityHint: 'নদী ও হাওর আহরণ'": "stockingDensityHint: 'Collected from rivers and haors'",
        "notes: 'মুক্ত জলাশ্যের রূপালী ছোট মাছ।'": "notes: 'A small silver fish from open waters.'",
        "stockingDensityHint: 'সংরক্ষণ প্রয়োজন (বিলুপ্তপ্রায় SIS)'": "stockingDensityHint: 'Conservation needed (endangered SIS)'",
        "notes: 'অত্যন্ত সুস্বাদু ও পুষ্টিকর বিলুপ্তপ্রায় দেশীয় ছোট মাছ।'": "notes: 'A very tasty and nutritious endangered native small fish.'",
        "stockingDensityHint: '৩ - ৫% (SIS সংমিশ্রণ)'": "stockingDensityHint: '3 - 5% (SIS polyculture)'",
        "notes: 'অগভীর জলাশয় ও ডোবার উপযোগী দেশীয় মাছ।'": "notes: 'A native fish suitable for shallow wetlands and channels.'",
        "stockingDensityHint: '২ - ৫%'": "stockingDensityHint: '2 - 5%'",
        "notes: 'বিলে প্রাকৃতিকভাবে বেড়ে ওঠা দেশীয় মাছ।'": "notes: 'A native fish naturally grown in beels.'",
        "stockingDensityHint: 'নদী, বিল ও কাদার তলদেশ'": "stockingDensityHint: 'River, beel, and muddy bottom'",
        "notes: 'পুকুরের তলার কাদায় গর্ত করে থাকে।'": "notes: 'Burrows into pond mud.',",
        "stockingDensityHint: 'কাদামাটি সম্বলিত খাঁচা/পিট চাষ'": "stockingDensityHint: 'Silt-based cage/peat culture'",
        "notes: 'রক্তস্বল্পতা দূরীকরণে ও আন্তর্জাতিক বাজারে রপ্তানি সম্ভাবনা সম্পন্ন।'": "notes: 'Potential for anemia treatment and international export markets.'",
        "stockingDensityHint: 'নদী ও ইষৎ লোনা পানি'": "stockingDensityHint: 'River and slightly saline water'",
        "notes: 'স্বাদু ও লোনা উভয় পানির মিষ্টি স্বাদের তলার মাছ।'": "notes: 'A tasty bottom fish for both fresh and slightly saline water.'",
        "stockingDensityHint: 'সমুদ্র থেকে আহরণকৃত (শুঁটকি ও তাজা)'": "stockingDensityHint: 'Collected from the sea (dried and fresh)'",
        "notes: 'কক্সবাজার ও উপকূলের বিখ্যাত সামুদ্রিক মাছ।'": "notes: 'A famous coastal fish from Cox's Bazar and the coast.'",
        "stockingDensityHint: 'সমুদ্র থেকে আহরণকৃত'": "stockingDensityHint: 'Collected from the sea'",
        "notes: 'শুঁটকির জন্য অত্যন্ত জনপ্রিয় সামুদ্রিক মাছ।'": "notes: 'A very popular marine fish for drying.'",
        "stockingDensityHint: 'উপকূল ও সমুদ্র থেকে আহরণকৃত'": "stockingDensityHint: 'Collected from the estuary and sea'",
        "notes: 'উপকূলীয় নোনা ও মিষ্টি পানির মোহনার মাছ।'": "notes: 'A mouth-watering fish of coastal brackish and fresh waters.'",
        "stockingDensityHint: 'মুক্ত নদী ও সমুদ্র (চাষ অযোগ্য)'": "stockingDensityHint: 'Open river and sea (non-culturable)'",
        "notes: 'বাংলাদেশের জাতীয় মাছ। দ্বিমুখী নিষেধাজ্ঞা (মা ইলিশ সংরক্ষণ ও জাটকা নিধন নিষেধাজ্ঞা) প্রযোজ্য।'": "notes: 'Bangladesh national fish. Dual restrictions apply (mother hilsa protection and jatka ban).',",
        "stockingDensityHint: 'নদী থেকে আহরণকৃত'": "stockingDensityHint: 'Collected from river'",
        "notes: 'নদীর সুস্বাদু কাঁটাময় চর্বিযুক্ত মাছ।'": "notes: 'A delicious river fish with fine bones and oily flesh.'",
        "stockingDensityHint: 'মোহনা ও নদী'": "stockingDensityHint: 'River mouth and river'",
        "notes: 'উচ্চ বাজারমূল্যের বিশেষ সুস্বাদু মাছ।'": "notes: 'A premium, high-market value fish.'",
        "stockingDensityHint: 'বিল ও নদী'": "stockingDensityHint: 'Beel and river'",
        "notes: 'কাচের মতো স্বচ্ছ ছোট দেশীয় মাছ।'": "notes: 'A glass-like small native fish.'",
        "stockingDensityHint: 'পাহাড়ী ছড়া ও নদী'": "stockingDensityHint: 'Hill streams and rivers'",
        "notes: 'সুন্দর ডোরাকাটা আকর্ষনীয় দেশীয় রূপালী মাছ।'": "notes: 'A beautiful native silver fish with vertical stripes.'",
        "stockingDensityHint: 'গভীর সমুদ্র থেকে আহরণকৃত'": "stockingDensityHint: 'Collected from deep sea'",
        "notes: 'সমুদ্রের আসল রূপচাঁদা। (ফার্মের রূপচাঁদা বা পাকু মাছের থেকে আলাদা)।'": "notes: 'True marine pomfret. (Different from farmed pomfret or Pacu fish.)',",
        "stockingDensityHint: 'সমুদ্র থেকে আহরণকৃত'": "stockingDensityHint: 'Collected from the sea'",
        "notes: 'গভীর সমুদ্রের বাণিজ্যিক মাছ।'": "notes: 'A commercially important deep-sea fish.'",
        "stockingDensityHint: 'পুকুর ও খালের ঝোপঝাড়'": "stockingDensityHint: 'Ponds and canal thickets'",
        "notes: 'ছোট দেশীয় গুড়া চিংড়ি। রান্নায় স্বাদ বাড়ায়।'": "notes: 'A small native freshwater shrimp that enhances cooking flavor.'",
        "categoryBn: CATEGORY_TRANSLATIONS[fish.category] || fish.category,": "categoryBn: fish.category,",
        "nameBn: fish.commonNameBn,": "nameBn: fish.commonNameEn,",
        "cultureTypeBn: fish.isBannedSpecies ? 'নিষিদ্ধ প্রজাতি' : fish.isCaptureOnly ? 'উন্মুক্ত জলাশয় (Capture)' : 'পুকুরে মিশ্র চাষ উপযোগী',": "cultureTypeBn: fish.isBannedSpecies ? 'Banned species' : fish.isCaptureOnly ? 'Capture only' : 'Suitable for mixed pond farming',",
        "pondZoneBn: fish.depthLayer === 'surface' ? 'উপরিভাগ (Surface)' : fish.depthLayer === 'column' ? 'মধ্যস্তর (Column)' : fish.depthLayer === 'bottom' ? 'তলদেশ (Bottom)' : 'সীমানা (Air-breathing)',": "pondZoneBn: fish.depthLayer === 'surface' ? 'Surface' : fish.depthLayer === 'column' ? 'Column' : fish.depthLayer === 'bottom' ? 'Bottom' : 'Boundary (Air-breathing)',",
    },
}

for file_path, mapping in changes.items():
    path = Path(file_path)
    text = path.read_text(encoding='utf-8')
    for old, new in mapping.items():
        if old not in text:
            raise RuntimeError(f"Expected text not found in {file_path}: {old}")
        text = text.replace(old, new)
    path.write_text(text, encoding='utf-8')
    print(f'Updated {file_path}')
