<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class KaliakoirDealersSeeder extends Seeder
{
    public function run(): void
    {
        $rows = [
            [
                'id' => 2,
                'user_id' => null,
                'shop_name' => 'মা ভেড়া পোল্ট্রি ফার্ম',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ তোফাজ্জল হোসেন',
                'product_name' => 'ভেড়া',
                'sector' => 'livestock',
                'address' => 'ঢালজোড়া, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01802252697',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'user_id' => null,
                'shop_name' => 'চন্দ্রা পেঁয়াজ এন্টারপ্রাইজ',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ মোখলেসুর রহমান',
                'product_name' => 'পেঁয়াজ',
                'sector' => 'crop',
                'address' => 'জাথালিয়া, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01654831499',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'user_id' => null,
                'shop_name' => 'বিসমিল্লাহ ভেড়া গবাদি পশু খামার',
                'shop_type' => 'general',
                'owner_name' => 'মোছাঃ মর্জিনা খাতুন',
                'product_name' => 'ভেড়া',
                'sector' => 'livestock',
                'address' => 'আটাবহ, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01585695963',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'user_id' => null,
                'shop_name' => 'শাপলা মাগুর মৎস্য আড়ৎ',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ কবির হোসেন',
                'product_name' => 'মাগুর মাছ',
                'sector' => 'fish',
                'address' => 'জাথালিয়া, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01432426091',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'user_id' => null,
                'shop_name' => 'সোনালী কবুতর পোল্ট্রি ফার্ম',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ জসিম উদ্দিন',
                'product_name' => 'কবুতর',
                'sector' => 'livestock',
                'address' => 'আটাবহ, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01349433297',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'user_id' => null,
                'shop_name' => 'নিউ গরু পোল্ট্রি ফার্ম',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ শফিকুল ইসলাম',
                'product_name' => 'গরু',
                'sector' => 'livestock',
                'address' => 'তালতলা বাজার, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01432188400',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'user_id' => null,
                'shop_name' => 'শাপলা ভুট্টা কৃষি ভান্ডার',
                'shop_type' => 'general',
                'owner_name' => 'মোছাঃ সালমা আক্তার',
                'product_name' => 'ভুট্টা',
                'sector' => 'crop',
                'address' => 'বান্নাল, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01675550046',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'user_id' => null,
                'shop_name' => 'দোয়েল কলা ট্রেডার্স',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ ফরহাদ হোসেন',
                'product_name' => 'কলা',
                'sector' => 'crop',
                'address' => 'সফিপুর, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01509233267',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'user_id' => null,
                'shop_name' => 'একতা আখ কৃষি ঘর',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ সেলিম মিয়া',
                'product_name' => 'আখ',
                'sector' => 'crop',
                'address' => 'বড়ইবাড়ী, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01310758148',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 11,
                'user_id' => null,
                'shop_name' => 'চন্দ্রা মাগুর হ্যাচারি',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ নজরুল ইসলাম',
                'product_name' => 'মাগুর মাছ',
                'sector' => 'fish',
                'address' => 'চন্দ্রা, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01893485067',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 12,
                'user_id' => null,
                'shop_name' => 'সোনালী আলু কৃষি ঘর',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ সাইফুল ইসলাম',
                'product_name' => 'আলু',
                'sector' => 'crop',
                'address' => 'চাপাইর, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01304823117',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 13,
                'user_id' => null,
                'shop_name' => 'আল্লাহর দান আখ বীজ ভান্ডার',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ রুহুল আমিন',
                'product_name' => 'আখ',
                'sector' => 'crop',
                'address' => 'বান্নাল, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01847257908',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 14,
                'user_id' => null,
                'shop_name' => 'চন্দ্রা আখ ফসল ভান্ডার',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ আজিজুল হক',
                'product_name' => 'আখ',
                'sector' => 'crop',
                'address' => 'জাথালিয়া, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01810876781',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 15,
                'user_id' => null,
                'shop_name' => 'পপুলার সুপারি ফসল ভান্ডার',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ সিরাজুল ইসলাম',
                'product_name' => 'সুপারি',
                'sector' => 'crop',
                'address' => 'আটাবহ, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01783157058',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 16,
                'user_id' => null,
                'shop_name' => 'দোয়েল পাট কৃষি ভান্ডার',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ মজিবুর রহমান',
                'product_name' => 'পাট',
                'sector' => 'crop',
                'address' => 'কালিয়াকৈর সদর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01829046146',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 17,
                'user_id' => null,
                'shop_name' => 'চন্দ্রা আখ এন্টারপ্রাইজ',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ আমিনুল ইসলাম',
                'product_name' => 'আখ',
                'sector' => 'crop',
                'address' => 'জাথালিয়া, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01895896392',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 18,
                'user_id' => null,
                'shop_name' => 'সততা হাঁস এগ্রো ফার্ম',
                'shop_type' => 'general',
                'owner_name' => 'মোছাঃ রহিমা বেগম',
                'product_name' => 'হাঁস',
                'sector' => 'livestock',
                'address' => 'ফুলবাড়িয়া, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01310156798',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 19,
                'user_id' => null,
                'shop_name' => 'দোয়েল শিং মৎস্য আড়ৎ',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ শাহিন আলম',
                'product_name' => 'শিং মাছ',
                'sector' => 'fish',
                'address' => 'মধ্যপাড়া, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01621307826',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 20,
                'user_id' => null,
                'shop_name' => 'শাপলা আলু কৃষি ঘর',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ তোফাজ্জল হোসেন',
                'product_name' => 'আলু',
                'sector' => 'crop',
                'address' => 'ফুলবাড়িয়া, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01757803035',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 21,
                'user_id' => null,
                'shop_name' => 'মেসার্স রুই ফিশারিজ',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ দেলোয়ার হোসেন',
                'product_name' => 'রুই মাছ',
                'sector' => 'fish',
                'address' => 'আটাবহ, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01934916196',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 22,
                'user_id' => null,
                'shop_name' => 'বিসমিল্লাহ পেঁয়াজ ফসল ভান্ডার',
                'shop_type' => 'general',
                'owner_name' => 'মোছাঃ শাহনাজ পারভীন',
                'product_name' => 'পেঁয়াজ',
                'sector' => 'crop',
                'address' => 'পল্লীবিদ্যুৎ বাজার, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01382389537',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 23,
                'user_id' => null,
                'shop_name' => 'আল্লাহর দান আলু বীজ ভান্ডার',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ মিজানুর রহমান',
                'product_name' => 'আলু',
                'sector' => 'crop',
                'address' => 'কালিয়াকৈর সদর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01674479482',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 24,
                'user_id' => null,
                'shop_name' => 'প্রগতি কলা কৃষি ভান্ডার',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ ইকবাল হোসেন',
                'product_name' => 'কলা',
                'sector' => 'crop',
                'address' => 'জাথালিয়া, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01555525990',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 25,
                'user_id' => null,
                'shop_name' => 'নিউ সিলভার হ্যাচারি',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ রশিদুল ইসলাম',
                'product_name' => 'সিলভার কার্প',
                'sector' => 'fish',
                'address' => 'বান্নাল, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01409587921',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 26,
                'user_id' => null,
                'shop_name' => 'মেসার্স গ্রাস এগ্রো ফিশারিজ',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ কামাল হোসেন',
                'product_name' => 'গ্রাস কার্প',
                'sector' => 'fish',
                'address' => 'সূত্রাপুর, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01338379072',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 27,
                'user_id' => null,
                'shop_name' => 'সততা হাঁস পশু হাট ভান্ডার',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ কবির হোসেন',
                'product_name' => 'হাঁস',
                'sector' => 'livestock',
                'address' => 'সফিপুর, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01985733141',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 28,
                'user_id' => null,
                'shop_name' => 'চন্দ্রা গ্রাস হ্যাচারি',
                'shop_type' => 'general',
                'owner_name' => 'মোছাঃ সালমা আক্তার',
                'product_name' => 'গ্রাস কার্প',
                'sector' => 'fish',
                'address' => 'ঢালজোড়া, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01858176612',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 29,
                'user_id' => null,
                'shop_name' => 'সততা সরিষা ট্রেডার্স',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ শাহজাহান আলী',
                'product_name' => 'সরিষা',
                'sector' => 'crop',
                'address' => 'পল্লীবিদ্যুৎ বাজার, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01888640684',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 30,
                'user_id' => null,
                'shop_name' => 'কালিয়াকৈর শাকসবজি কৃষি ঘর',
                'shop_type' => 'general',
                'owner_name' => 'মোছাঃ শাহনাজ পারভীন',
                'product_name' => 'শাকসবজি',
                'sector' => 'crop',
                'address' => 'মৌচাক, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01999687802',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 31,
                'user_id' => null,
                'shop_name' => 'কালিয়াকৈর ভেড়া পোল্ট্রি ফার্ম',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ কামাল হোসেন',
                'product_name' => 'ভেড়া',
                'sector' => 'livestock',
                'address' => 'তালতলা বাজার, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01847785087',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 32,
                'user_id' => null,
                'shop_name' => 'জনতা পেঁয়াজ ফসল ভান্ডার',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ শাহজাহান আলী',
                'product_name' => 'পেঁয়াজ',
                'sector' => 'crop',
                'address' => 'চাপাইর, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01489400843',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 33,
                'user_id' => null,
                'shop_name' => 'প্রগতি পাট এন্টারপ্রাইজ',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ ফজলুল হক',
                'product_name' => 'পাট',
                'sector' => 'crop',
                'address' => 'সূত্রাপুর, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01471671490',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 34,
                'user_id' => null,
                'shop_name' => 'গ্রামীণ তেলাপিয়া মৎস্য বীজ খামার',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ রশিদুল ইসলাম',
                'product_name' => 'তেলাপিয়া মাছ',
                'sector' => 'fish',
                'address' => 'জাথালিয়া, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01435642376',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 35,
                'user_id' => null,
                'shop_name' => 'কালিয়াকৈর হাঁস লাইভস্টক এন্টারপ্রাইজ',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ রফিকুল ইসলাম',
                'product_name' => 'হাঁস',
                'sector' => 'livestock',
                'address' => 'বড়ইবাড়ী, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01580147467',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 36,
                'user_id' => null,
                'shop_name' => 'আধুনিক ছাগল ডেইরি ফার্ম',
                'shop_type' => 'general',
                'owner_name' => 'মোছাঃ শাহনাজ পারভীন',
                'product_name' => 'ছাগল',
                'sector' => 'livestock',
                'address' => 'মৌচাক, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01484999353',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 37,
                'user_id' => null,
                'shop_name' => 'একতা মহিষ এগ্রো ফার্ম',
                'shop_type' => 'general',
                'owner_name' => 'মোছাঃ ফাতেমা খাতুন',
                'product_name' => 'মহিষ',
                'sector' => 'livestock',
                'address' => 'আটাবহ, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01658278939',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 38,
                'user_id' => null,
                'shop_name' => 'প্রগতি ছাগল ডেইরি ফার্ম',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ মোতালেব হোসেন',
                'product_name' => 'ছাগল',
                'sector' => 'livestock',
                'address' => 'চাপাইর, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01965256718',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 39,
                'user_id' => null,
                'shop_name' => 'কালিয়াকৈর হাঁস পশু হাট ভান্ডার',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ বাবুল মিয়া',
                'product_name' => 'হাঁস',
                'sector' => 'livestock',
                'address' => 'বড়ইবাড়ী, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01499375758',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 40,
                'user_id' => null,
                'shop_name' => 'নিউ সিলভার হ্যাচারি',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ আব্দুল করিম',
                'product_name' => 'সিলভার কার্প',
                'sector' => 'fish',
                'address' => 'বান্নাল, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01670406028',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 41,
                'user_id' => null,
                'shop_name' => 'সোনালী পেঁয়াজ ফসল ভান্ডার',
                'shop_type' => 'general',
                'owner_name' => 'মোছাঃ ফাতেমা খাতুন',
                'product_name' => 'পেঁয়াজ',
                'sector' => 'crop',
                'address' => 'তালতলা বাজার, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01432000130',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 42,
                'user_id' => null,
                'shop_name' => 'একতা কাতলা মৎস্য বীজ খামার',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ রফিকুল ইসলাম',
                'product_name' => 'কাতলা মাছ',
                'sector' => 'fish',
                'address' => 'মৌচাক, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01611075904',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 43,
                'user_id' => null,
                'shop_name' => 'মেসার্স আম বাণিজ্যালয়',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ মাহবুবুর রহমান',
                'product_name' => 'আম',
                'sector' => 'crop',
                'address' => 'ঢালজোড়া, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01983646898',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 44,
                'user_id' => null,
                'shop_name' => 'বিসমিল্লাহ কাতলা এগ্রো ফিশারিজ',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ সেলিম মিয়া',
                'product_name' => 'কাতলা মাছ',
                'sector' => 'fish',
                'address' => 'তালতলা বাজার, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01343305106',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 45,
                'user_id' => null,
                'shop_name' => 'প্রগতি আলু বাণিজ্যালয়',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ মাহবুবুর রহমান',
                'product_name' => 'আলু',
                'sector' => 'crop',
                'address' => 'চন্দ্রা, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01614385339',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 46,
                'user_id' => null,
                'shop_name' => 'মা কই মৎস্য আড়ৎ',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ নাসির উদ্দিন',
                'product_name' => 'কই মাছ',
                'sector' => 'fish',
                'address' => 'মধ্যপাড়া, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01389480162',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 47,
                'user_id' => null,
                'shop_name' => 'জনতা সুপারি বাণিজ্যালয়',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ শামসুল হক',
                'product_name' => 'সুপারি',
                'sector' => 'crop',
                'address' => 'তালতলা বাজার, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01771047957',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 48,
                'user_id' => null,
                'shop_name' => 'শাপলা ছাগল পোল্ট্রি ফার্ম',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ আক্তার হোসেন',
                'product_name' => 'ছাগল',
                'sector' => 'livestock',
                'address' => 'মৌচাক, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01384034145',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 49,
                'user_id' => null,
                'shop_name' => 'কালিয়াকৈর মাগুর হ্যাচারি',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ শামসুল হক',
                'product_name' => 'মাগুর মাছ',
                'sector' => 'fish',
                'address' => 'ফুলবাড়িয়া, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01598603098',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 50,
                'user_id' => null,
                'shop_name' => 'বিসমিল্লাহ মহিষ ডেইরি ফার্ম',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ জসিম উদ্দিন',
                'product_name' => 'মহিষ',
                'sector' => 'livestock',
                'address' => 'জাথালিয়া, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01758695493',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 51,
                'user_id' => null,
                'shop_name' => 'আধুনিক শাকসবজি বাণিজ্যালয়',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ কবির হোসেন',
                'product_name' => 'শাকসবজি',
                'sector' => 'crop',
                'address' => 'ঢালজোড়া, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01390887033',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 52,
                'user_id' => null,
                'shop_name' => 'বিসমিল্লাহ পাঙ্গাশ হ্যাচারি',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ নজরুল ইসলাম',
                'product_name' => 'পাঙ্গাশ মাছ',
                'sector' => 'fish',
                'address' => 'বান্নাল, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01852225520',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 53,
                'user_id' => null,
                'shop_name' => 'মেসার্স শিং মৎস্য আড়ৎ',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ শামসুল হক',
                'product_name' => 'শিং মাছ',
                'sector' => 'fish',
                'address' => 'ঢালজোড়া, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01398566847',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 54,
                'user_id' => null,
                'shop_name' => 'গ্রামীণ ছাগল পোল্ট্রি ফার্ম',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ আনোয়ার হোসেন',
                'product_name' => 'ছাগল',
                'sector' => 'livestock',
                'address' => 'মৌচাক, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01904962363',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 55,
                'user_id' => null,
                'shop_name' => 'শাপলা ভেড়া পশু হাট ভান্ডার',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ হাবিবুর রহমান',
                'product_name' => 'ভেড়া',
                'sector' => 'livestock',
                'address' => 'পল্লীবিদ্যুৎ বাজার, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01969895276',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 56,
                'user_id' => null,
                'shop_name' => 'আধুনিক কই মৎস্য আড়ৎ',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ শহিদুল ইসলাম',
                'product_name' => 'কই মাছ',
                'sector' => 'fish',
                'address' => 'তালতলা বাজার, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01649682248',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 57,
                'user_id' => null,
                'shop_name' => 'চন্দ্রা আলু কৃষি ঘর',
                'shop_type' => 'general',
                'owner_name' => 'মোছাঃ রহিমা বেগম',
                'product_name' => 'আলু',
                'sector' => 'crop',
                'address' => 'মৌচাক, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01404512492',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 58,
                'user_id' => null,
                'shop_name' => 'আধুনিক কবুতর এগ্রো ফার্ম',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ জাহাঙ্গীর আলম',
                'product_name' => 'কবুতর',
                'sector' => 'livestock',
                'address' => 'সূত্রাপুর, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01520620309',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 59,
                'user_id' => null,
                'shop_name' => 'নিউ কাতলা মৎস্য বীজ খামার',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ মাহবুবুর রহমান',
                'product_name' => 'কাতলা মাছ',
                'sector' => 'fish',
                'address' => 'মৌচাক, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01571807935',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 60,
                'user_id' => null,
                'shop_name' => 'নিউ চিংড়ি মৎস্য ভান্ডার',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ মোস্তফা কামাল',
                'product_name' => 'চিংড়ি মাছ',
                'sector' => 'fish',
                'address' => 'চন্দ্রা, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01710645059',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 61,
                'user_id' => null,
                'shop_name' => 'শাপলা হাঁস পশু হাট ভান্ডার',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ আজিজুল হক',
                'product_name' => 'হাঁস',
                'sector' => 'livestock',
                'address' => 'মৌচাক, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01305705762',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 62,
                'user_id' => null,
                'shop_name' => 'শাপলা ভেড়া পোল্ট্রি ফার্ম',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ মজিবুর রহমান',
                'product_name' => 'ভেড়া',
                'sector' => 'livestock',
                'address' => 'চাপাইর, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01959416347',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 63,
                'user_id' => null,
                'shop_name' => 'প্রগতি হাঁস লাইভস্টক এন্টারপ্রাইজ',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ ইকবাল হোসেন',
                'product_name' => 'হাঁস',
                'sector' => 'livestock',
                'address' => 'বড়ইবাড়ী, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01843598460',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 64,
                'user_id' => null,
                'shop_name' => 'কালিয়াকৈর ছাগল লাইভস্টক এন্টারপ্রাইজ',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ শাহাদাত হোসেন',
                'product_name' => 'ছাগল',
                'sector' => 'livestock',
                'address' => 'জাথালিয়া, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01327727829',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 65,
                'user_id' => null,
                'shop_name' => 'একতা কই মৎস্য আড়ৎ',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ রশিদুল ইসলাম',
                'product_name' => 'কই মাছ',
                'sector' => 'fish',
                'address' => 'মধ্যপাড়া, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01494920316',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 66,
                'user_id' => null,
                'shop_name' => 'আল্লাহর দান গরু ডেইরি ফার্ম',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ ইব্রাহিম খলিল',
                'product_name' => 'গরু',
                'sector' => 'livestock',
                'address' => 'মধ্যপাড়া, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01425404996',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 67,
                'user_id' => null,
                'shop_name' => 'মেসার্স কবুতর এগ্রো ফার্ম',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ আমিনুল ইসলাম',
                'product_name' => 'কবুতর',
                'sector' => 'livestock',
                'address' => 'সূত্রাপুর, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01839303467',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 68,
                'user_id' => null,
                'shop_name' => 'গ্রামীণ কলা ট্রেডার্স',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ দেলোয়ার হোসেন',
                'product_name' => 'কলা',
                'sector' => 'crop',
                'address' => 'মধ্যপাড়া, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01896089347',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 69,
                'user_id' => null,
                'shop_name' => 'দোয়েল শিং মৎস্য ভান্ডার',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ জাহাঙ্গীর আলম',
                'product_name' => 'শিং মাছ',
                'sector' => 'fish',
                'address' => 'মৌচাক, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01678845769',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 70,
                'user_id' => null,
                'shop_name' => 'বিসমিল্লাহ মুরগি লাইভস্টক এন্টারপ্রাইজ',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ মোতালেব হোসেন',
                'product_name' => 'মুরগি',
                'sector' => 'livestock',
                'address' => 'তালতলা বাজার, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01916689038',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 71,
                'user_id' => null,
                'shop_name' => 'মেসার্স সিলভার ফিশারিজ',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ আলাউদ্দিন',
                'product_name' => 'সিলভার কার্প',
                'sector' => 'fish',
                'address' => 'বান্নাল, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01446857315',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 72,
                'user_id' => null,
                'shop_name' => 'বিসমিল্লাহ ভেড়া লাইভস্টক এন্টারপ্রাইজ',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ কামাল হোসেন',
                'product_name' => 'ভেড়া',
                'sector' => 'livestock',
                'address' => 'কালিয়াকৈর সদর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01728190218',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 73,
                'user_id' => null,
                'shop_name' => 'পপুলার তেলাপিয়া মৎস্য বীজ খামার',
                'shop_type' => 'general',
                'owner_name' => 'মোছাঃ রোকেয়া বেগম',
                'product_name' => 'তেলাপিয়া মাছ',
                'sector' => 'fish',
                'address' => 'সূত্রাপুর, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01920098486',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 74,
                'user_id' => null,
                'shop_name' => 'আধুনিক পাঙ্গাশ মৎস্য আড়ৎ',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ আক্তার হোসেন',
                'product_name' => 'পাঙ্গাশ মাছ',
                'sector' => 'fish',
                'address' => 'আটাবহ, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01455388009',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 75,
                'user_id' => null,
                'shop_name' => 'নিউ চিংড়ি মৎস্য আড়ৎ',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ মোস্তফা কামাল',
                'product_name' => 'চিংড়ি মাছ',
                'sector' => 'fish',
                'address' => 'মৌচাক, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01627978455',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 76,
                'user_id' => null,
                'shop_name' => 'মা পাট ট্রেডার্স',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ নাসির উদ্দিন',
                'product_name' => 'পাট',
                'sector' => 'crop',
                'address' => 'ঢালজোড়া, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01675804773',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 77,
                'user_id' => null,
                'shop_name' => 'চন্দ্রা মহিষ লাইভস্টক এন্টারপ্রাইজ',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ ইলিয়াস হোসেন',
                'product_name' => 'মহিষ',
                'sector' => 'livestock',
                'address' => 'কালিয়াকৈর সদর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01531846142',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 78,
                'user_id' => null,
                'shop_name' => 'ইসলামিয়া কাতলা ফিশারিজ',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ রশিদুল ইসলাম',
                'product_name' => 'কাতলা মাছ',
                'sector' => 'fish',
                'address' => 'জাথালিয়া, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01383950583',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 79,
                'user_id' => null,
                'shop_name' => 'গ্রামীণ কবুতর গবাদি পশু খামার',
                'shop_type' => 'general',
                'owner_name' => 'মোছাঃ রোকেয়া বেগম',
                'product_name' => 'কবুতর',
                'sector' => 'livestock',
                'address' => 'ঢালজোড়া, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01629250309',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 80,
                'user_id' => null,
                'shop_name' => 'আল্লাহর দান চিংড়ি মৎস্য বীজ খামার',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ নাসির উদ্দিন',
                'product_name' => 'চিংড়ি মাছ',
                'sector' => 'fish',
                'address' => 'বান্নাল, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01907805251',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 81,
                'user_id' => null,
                'shop_name' => 'কৃষক মহিষ পোল্ট্রি ফার্ম',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ জসিম উদ্দিন',
                'product_name' => 'মহিষ',
                'sector' => 'livestock',
                'address' => 'কালিয়াকৈর সদর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01828465257',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 82,
                'user_id' => null,
                'shop_name' => 'প্রগতি আখ এন্টারপ্রাইজ',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ রশিদুল ইসলাম',
                'product_name' => 'আখ',
                'sector' => 'crop',
                'address' => 'মৌচাক, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01999717822',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 83,
                'user_id' => null,
                'shop_name' => 'সততা ধান ট্রেডার্স',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ কবির হোসেন',
                'product_name' => 'ধান',
                'sector' => 'crop',
                'address' => 'চন্দ্রা, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01864117260',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 84,
                'user_id' => null,
                'shop_name' => 'একতা কলা এন্টারপ্রাইজ',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ ফরিদ উদ্দিন',
                'product_name' => 'কলা',
                'sector' => 'crop',
                'address' => 'মধ্যপাড়া, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01360101630',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 85,
                'user_id' => null,
                'shop_name' => 'পপুলার কলা এন্টারপ্রাইজ',
                'shop_type' => 'general',
                'owner_name' => 'মোছাঃ নাসিমা বেগম',
                'product_name' => 'কলা',
                'sector' => 'crop',
                'address' => 'চাপাইর, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01407758191',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 86,
                'user_id' => null,
                'shop_name' => 'বিসমিল্লাহ সিলভার এগ্রো ফিশারিজ',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ ওয়াহিদুজ্জামান',
                'product_name' => 'সিলভার কার্প',
                'sector' => 'fish',
                'address' => 'আটাবহ, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01860152475',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 87,
                'user_id' => null,
                'shop_name' => 'মা গ্রাস এগ্রো ফিশারিজ',
                'shop_type' => 'general',
                'owner_name' => 'মোছাঃ জোসনা বেগম',
                'product_name' => 'গ্রাস কার্প',
                'sector' => 'fish',
                'address' => 'মৌচাক, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01793541269',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 88,
                'user_id' => null,
                'shop_name' => 'একতা ভুট্টা এন্টারপ্রাইজ',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ বাবুল মিয়া',
                'product_name' => 'ভুট্টা',
                'sector' => 'crop',
                'address' => 'মৌচাক, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01860308211',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 89,
                'user_id' => null,
                'shop_name' => 'কালিয়াকৈর গরু পশু হাট ভান্ডার',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ মোস্তফা কামাল',
                'product_name' => 'গরু',
                'sector' => 'livestock',
                'address' => 'জাথালিয়া, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01529740705',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 90,
                'user_id' => null,
                'shop_name' => 'শাপলা সিলভার এগ্রো ফিশারিজ',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ মোখলেসুর রহমান',
                'product_name' => 'সিলভার কার্প',
                'sector' => 'fish',
                'address' => 'চন্দ্রা, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01387061039',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 91,
                'user_id' => null,
                'shop_name' => 'সোনালী রুই মৎস্য আড়ৎ',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ সেলিম মিয়া',
                'product_name' => 'রুই মাছ',
                'sector' => 'fish',
                'address' => 'চন্দ্রা, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01716586545',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 92,
                'user_id' => null,
                'shop_name' => 'জনতা চিংড়ি হ্যাচারি',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ সাইফুল ইসলাম',
                'product_name' => 'চিংড়ি মাছ',
                'sector' => 'fish',
                'address' => 'বান্নাল, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01949013457',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 93,
                'user_id' => null,
                'shop_name' => 'গ্রামীণ কলা ফসল ভান্ডার',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ শহিদুল ইসলাম',
                'product_name' => 'কলা',
                'sector' => 'crop',
                'address' => 'মধ্যপাড়া, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01488626620',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 94,
                'user_id' => null,
                'shop_name' => 'আধুনিক চিংড়ি ফিশারিজ',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ আক্তার হোসেন',
                'product_name' => 'চিংড়ি মাছ',
                'sector' => 'fish',
                'address' => 'ফুলবাড়িয়া, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01936678201',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 95,
                'user_id' => null,
                'shop_name' => 'ইসলামিয়া মহিষ ডেইরি ফার্ম',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ মাহবুবুর রহমান',
                'product_name' => 'মহিষ',
                'sector' => 'livestock',
                'address' => 'মৌচাক, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01607109378',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 96,
                'user_id' => null,
                'shop_name' => 'জনতা গম ট্রেডার্স',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ মোস্তফা কামাল',
                'product_name' => 'গম',
                'sector' => 'crop',
                'address' => 'চন্দ্রা, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01853379368',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 97,
                'user_id' => null,
                'shop_name' => 'কৃষক সিলভার ফিশারিজ',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ ফরহাদ হোসেন',
                'product_name' => 'সিলভার কার্প',
                'sector' => 'fish',
                'address' => 'কালিয়াকৈর সদর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01686241922',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 98,
                'user_id' => null,
                'shop_name' => 'ইসলামিয়া পাট কৃষি ভান্ডার',
                'shop_type' => 'general',
                'owner_name' => 'মোছাঃ জোসনা বেগম',
                'product_name' => 'পাট',
                'sector' => 'crop',
                'address' => 'আটাবহ, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01884924613',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 99,
                'user_id' => null,
                'shop_name' => 'গ্রামীণ সিলভার মৎস্য বীজ খামার',
                'shop_type' => 'general',
                'owner_name' => 'মোছাঃ সালমা আক্তার',
                'product_name' => 'সিলভার কার্প',
                'sector' => 'fish',
                'address' => 'ফুলবাড়িয়া, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01598423636',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 100,
                'user_id' => null,
                'shop_name' => 'নিউ চিংড়ি মৎস্য ভান্ডার',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ জসিম উদ্দিন',
                'product_name' => 'চিংড়ি মাছ',
                'sector' => 'fish',
                'address' => 'জাথালিয়া, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01635252172',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 101,
                'user_id' => null,
                'shop_name' => 'মা মাগুর মৎস্য আড়ৎ',
                'shop_type' => 'general',
                'owner_name' => 'মোঃ নজরুল ইসলাম',
                'product_name' => 'মাগুর মাছ',
                'sector' => 'fish',
                'address' => 'মধ্যপাড়া, কালিয়াকৈর, গাজীপুর',
                'upazila_id' => 28,
                'phone' => '01681106046',
                'avg_rating' => 0,
                'review_count' => 0,
                'is_verified' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ];

        DB::table('dealers')->upsert($rows, ['id'], [
            'user_id', 'shop_name', 'shop_type', 'owner_name', 'product_name', 'sector',
            'address', 'upazila_id', 'phone', 'avg_rating', 'review_count', 'is_verified',
        ]);
    }
}
